name: µLang language

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pylint mypy pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check with ruff
      run: |
        ruff check .
    - name: Lint with pylint
      run: |
        pylint --init-hook='import sys; sys.path.append(".")' .
    - name: Check tyes with mypy
      run: |
        mypy --follow-imports=skip --ignore-missing-imports --check-untyped-defs .
    - name: Test with pytest
      run: |
        pytest
